### ISSUE TITLE
Pytorch model can't run on GPU

### ISSUE THREAD

**Issue by duckduck-sys** [daniegr/EfficientPose#17]
Loading the pytorch model with 

```
model = load(join('models', 'pytorch', 'EfficientPose{0}'.format(model_variant.upper())), map_location=device)
model = model.to(device)
```

and transfering the input tensor to GPU device with

`batch = from_numpy(batch).batch.to(device)`

and running

`batch_outputs = model(batch)`

gets the following error:

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

Why can't the PyTorch mode run on GPU?

**Comment by daniegr** [comment]
@duckduck-sys: The GPU support of EfficientPose with PyTorch has not yet been extensively tested, so for now I would recommend you to turn to the TensorFlow version of EfficientPose. Nevertheless, if you manage to get the PyTorch models up and running on GPUs, I would be glad if you could share your solution.

**Comment by faresbs** [comment]
In order to run the efficient pose on GPU, you have to do two things.
First, you need to load the constant tensors (torch.autograd.Variable) in the forward pass to GPU as they are loaded by default to CPU. So you can simply do : `self.pass1_block1_mbconv1_skeleton_conv1_eswish_mul_x = torch.autograd.Variable(torch.Tensor([1.25]), requires_grad=False).to("cuda:0")`
And apply the same thing to the other constant tensors below it.
Second, you need to also load the custom Transpose2d layer to GPU in the __transposed function. You can do this by doing : `return helpers.pytorch_BilinearConvTranspose2d(channels=channels, kernel_size=kernel_size, stride=stride).to("cuda:0")`

This is a quick and dirty solution, you can instead load these to your current device (CPU/GPU). Hope this can be helpful to someone :)
