### ISSUE TITLE
Transpose Conv layer, learned or fixed ?

### ISSUE THREAD

**Issue by ravi-dhime** [daniegr/EfficientPose#41]
Thank you @daniegr for sharing the great work!

I have a question on the bilinear transpose conv2d used in your pytorch model. 

From the FCN paper referenced in your paper, it looks like the intention is 
1. to initialize the weights of the transpose conv2d with bilinear weights and 
2. then to let the training process modify the weights

However, the pytorch inference implementation of the efficientpose model
1. seems to create new transpose conv2d objects in each forward pass, initialized with the bilinear weights and
2. does not seem to load weights into the transpose layers from the weights file

So, is it intentional to keep the weights fixed as bilinear weights ? if yes, can we just use torch.nn.Upsampling ? Please clarify

**Comment by daniegr** [comment]
@ravi-dhime: Thank you for the valuable comment. To clarify, 1) it is correct that the weights of the transposed convolutions should remain fixed in accordance with bilinear interpolation by using a 4x4 neighborhood, and 2) if torch.nn.Upsampling produces the same outputs as our custom transposed convolutions, feel free to go with the official method.

**Comment by ravi-dhime** [comment]
thank you @daniegr for confirming that the transpose conv weights are fixed.

And looks like the Upsampling is different from Transpose Conv. Will stick with your implementation of the Transpose Conv.
